export const mjrThemeVars = {
  errorText: "var(--mjr-error, #e66)",
  successGradient: "var(--mjr-success-gradient, linear-gradient(90deg, #22c55e, #16a34a))",
  statusSuccess: "var(--mjr-status-success, #65d174)",
  statusError: "var(--mjr-status-error, #d45a5a)",
  statusNeutral: "var(--mjr-status-neutral, #aaaaaa)",
  statusWarning: "var(--mjr-status-warning, #eab308)",
  statusSuccessGlow: "var(--mjr-status-success-glow, rgba(101, 209, 116, 0.9))",
  statusErrorGlow: "var(--mjr-status-error-glow, rgba(212, 90, 90, 0.8))",
  statusNeutralGlow: "var(--mjr-status-neutral-glow, rgba(170, 170, 170, 0.6))",
  starsFilled: "var(--mjr-stars-filled, #ffd45a)",
  starsEmpty: "var(--mjr-stars-empty, #777)",
  cardBg: "var(--mjr-card-bg, #111)",
  cardOverlay: "var(--mjr-card-overlay, rgba(0, 0, 0, 0.7))",
  highlight: "var(--comfy-accent, #5fb3ff)",
  badgeAccent: "var(--mjr-badge-accent, var(--comfy-accent, #5fb3ff))",
  badgeFg: "var(--mjr-badge-fg, #fff)",
  icon: "var(--mjr-icon-fg, #fff)",
  textColor: "var(--mjr-text-color, #eee)",
  errorBorder: "var(--mjr-error-border, #b33)",
  positiveField: "var(--mjr-positive-color, #8bd5ff)",
  negativeField: "var(--mjr-negative-color, #ff9f7f)",
  seedField: "var(--mjr-seed-color, #d1b3ff)",
  thumbBg: "var(--mjr-thumb-bg, #111)",
  filmstripBg: "var(--mjr-filmstrip-bg, rgba(255, 255, 255, 0.08))",
  errorBg: "var(--mjr-error-bg, rgba(180, 40, 40, 0.15))",
  audioGradient: "var(--mjr-audio-bg, linear-gradient(135deg, #1b2735 0%, #090a0f 100%))",
  modelGradient: "var(--mjr-model-bg, radial-gradient(circle at 20% 20%, #3b82f6, #0f172a))",
  sidebarBg: "var(--mjr-sidebar-bg, #050505)",
  viewerBg: "var(--mjr-viewer-bg, #000000cc)",
  viewerBorder: "var(--mjr-viewer-border, #555)",
  viewerText: "var(--mjr-viewer-text, #fff)",
  viewerPanel: "var(--mjr-viewer-panel, #111)",
  viewerPanelBorder: "var(--mjr-viewer-panel-border, #444)",
  viewerMuted: "var(--mjr-viewer-muted, #ddd)",
  viewerSmallText: "var(--mjr-viewer-small, #888)",
  viewerChecker: "var(--mjr-viewer-checker, repeating-conic-gradient(#eee 0 25%, #ccc 0 50%))",
  viewerCheckerBg: "var(--mjr-viewer-checker-bg, #000)",
  videoIconBg: "var(--mjr-video-icon-bg, linear-gradient(135deg, #1b2735 0%, #090a0f 100%))",
  overlay: "var(--mjr-overlay, #000000aa)",
};

export function mjrCssVar(name, fallback) {
  if (!name) return fallback || "";
  return fallback ? `var(${name}, ${fallback})` : `var(${name})`;
}
